# Generated by Django 5.0 on 2025-06-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Workload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=255, unique=True)),
                (
                    "credentials",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload",
                        to="migrations_app.credentials",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MountPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_size", models.IntegerField()),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount_points",
                        to="migrations_app.workload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigrationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cloud_type",
                    models.CharField(
                        choices=[
                            ("aws", "Aws"),
                            ("azure", "Azure"),
                            ("vsphere", "Vsphere"),
                            ("vcloud", "Vcloud"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cloud_credentials",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="migrations_app.credentials",
                    ),
                ),
                (
                    "target_vm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="migrations_app.workload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Migration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("running", "Running"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migrations",
                        to="migrations_app.migrationtarget",
                    ),
                ),
                (
                    "selected_mount_points",
                    models.ManyToManyField(
                        related_name="migrations", to="migrations_app.mountpoint"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_migrations",
                        to="migrations_app.workload",
                    ),
                ),
            ],
        ),
    ]
